### ISSUE TITLE
code 100% correct, but there is an easier way to do it

### ISSUE THREAD

**Issue by basharaq** [rebo-log/assignment10-js#1]
https://github.com/rebo-log/assignment10-js/blob/bdb96d969d948e1e132d6edfcd1c90dbc40c638f/task-1/index.js#L2

you could simply do this:

const result = [];

for (let i = 2; i <= 20; i+=2) {
    result.push(i);
}

console.log(result.join());

**Comment by rebo-log** [comment]
yes is more efficient but for some reason, if you put a large number like 100000 you have to loop from 0 100000 and the output becomes slow in my case I can put the 100000 in the array and it will just print it and if I want random list to be sorted this solution will not work

**Comment by basharaq** [comment]
you are absolutely correct. my suggestion is specific to only this question which asks for even numbers between 1 and 20.
if the question was more generic then yes, your solution will definitely be the only one.
