### ISSUE TITLE
code copied from internet

### ISSUE THREAD

**Issue by basharaq** [rebo-log/assignment10-js#7]
https://github.com/rebo-log/assignment10-js/blob/bdb96d969d948e1e132d6edfcd1c90dbc40c638f/task-7/index.js#L1

this seems to be a copy/paste from:
https://www.w3resource.com/javascript-exercises/javascript-array-exercise-8.php

i normally don't mind "stealing" as long as you fully understand what you "steal" ;)
can you at least explain to me the principle of how this code works?

**Comment by rebo-log** [comment]
I did read the explain and  understand about 50% of it any way I will not submit any assignment that not fully  writing by me for the code it becomes open source when they post it online so technically I can't  steal whet  it's already free 
articl link https://javascript.developreference.com/article/18294762/Find+the+most+frequent+item+of+an+array+(not+just+strings)

**Comment by basharaq** [comment]
well, from a legal perspective you are definitely right. that's why i put the word "steal" between double quotes ;)
like i said, i have no problem with this as long as you understand the code that you find. all developers do this to save time, but make sure to understand the code 100% because if there is a bug in it you will have to solve it :)
